import { Jost } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jost.className} antialiased`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
